version: "3.7"
services:

  mongo:
    image: mongo:4
    networks:
      - acheronet
    restart: always

  flagsubmitter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - acheronet
    command: python3 main.py

networks:
  acheronet:
